### ISSUE TITLE
AddEventTypes_PbindFx:makeSplitSynthDef is creating hidden txarcmeta file in $HOME

### ISSUE THREAD

**Issue by salkin-mada** [dkmayer/miSCellaneous_lib#2]
AddEventTypes_PbindFx:makeSplitSynthDef should use `.store` isntead of `.writeDefFile`
please see this [issue](https://github.com/supercollider/supercollider/issues/4872)

I think it would be a good idea to also use `.store` on AddEventTypes_PbindFx:makeSplitZeroSynthDef and AddEventTypes_PbindFx:makeZeroSynthDef

But for the bug, AddEventTypes_PbindFx:makeSplitSynthDef is the only method acting badly due to the need of making a txarcmeta file.

In general `.writeDefFile` seems a bit dangerous. Check this [issue](https://github.com/supercollider/supercollider/issues/4873)

**Comment by dkmayer** [comment]
Thanks for the report! I'll have a look at it, I'm planning to make an update release soon anyway, that can include the fix.

**Comment by dkmayer** [comment]
fixed in v0.23, just put online, thanks and cheers.
